language: cpp
os: linux
dist: focal
compiler:
  - clang
  - gcc
  
# matrix:
#   include:
#     - name: "GCC-10"
#       addons:
#         apt:
#           sources: ubuntu-toolchain-r-test
#           packages: g++-10
# 
#     - name: "GCC-8"
#       addons:
#         apt:
#           sources: ubuntu-toolchain-r-test
#           packages: g++-8
# 
#     - name: "Clang-10, libc++"
#       addons:
#         apt:
#           sources: llvm-toolchain-bionic-10
#           packages:
#             - clang-10
#             - libc++-10-dev
#             - libc++abi-10-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest . -V

